name: Build and Deploy Container App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: cloudquickstartregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build ./e-commerce-admin -t cloudquickstartregistry.azurecr.io/e-admin:0.0.${{ github.run_number }}
        docker push cloudquickstartregistry.azurecr.io/e-admin:0.0.${{ github.run_number }}

    - name: Logout from Azure Container Registry
      run: docker logout cloudquickstartregistry.azurecr.io
